function zdot=rhs(t,z,slip,tal,F_left,F_right)   

m_left_thigh=slip.m_thigh;
m_left_shank=slip.m_shank;
m_right_thigh=slip.m_thigh;
m_right_shank=slip.m_shank;
M=slip.M;
thigh_length=slip.thigh_length;
shank_length=slip.shank_length;
trunk_length=slip.trunk_length;
thigh_center_pos=slip.thigh_center_pos;
shank_center_pos=slip.shank_center_pos;
trunk_center_pos=slip.trunk_center_pos;

g=slip.g;
I1_2=slip.I1(3,3);
I2_2=slip.I2(3,3);
Itrunk2=slip.Itrunk(3,3);
% x=z(1);
% z=z(2);
phi=z(3);
leg_hip_angle_left=z(4);
leg_knee_angle_left=z(5);
leg_hip_angle_right=z(6);
leg_knee_angle_right=z(7);
dx=z(8);
dz=z(9);
dphi=z(10);
dleg_hip_angle_left=z(11);
dleg_knee_angle_left=z(12);
dleg_hip_angle_right=z(13);
dleg_knee_angle_right=z(14);

tal_hip_left=tal(1);
tal_hip_right=tal(2);
tal_knee_left=tal(3);
tal_knee_right=tal(4);
F1x=F_left(1);
F1z=F_left(3);
F2x=F_right(1);
F2z=F_right(3);

MM =[                                                                                                                                                                                                                                                                                                                                                                                           M + m_left_thigh + m_left_shank + m_right_thigh + m_right_shank,                                                                                                                                                                                                                                                                                                                                                                                                                                                          0, M*trunk_center_pos*cos(phi) - m_left_thigh*thigh_center_pos*cos(leg_hip_angle_left - phi) - m_right_shank*thigh_length*cos(leg_hip_angle_right - phi) - m_right_thigh*thigh_center_pos*cos(leg_hip_angle_right - phi) - m_left_shank*shank_center_pos*cos(leg_knee_angle_left - leg_hip_angle_left + phi) - m_right_shank*shank_center_pos*cos(leg_knee_angle_right - leg_hip_angle_right + phi) - m_left_shank*thigh_length*cos(leg_hip_angle_left - phi), m_left_shank*thigh_length*cos(leg_hip_angle_left - phi) + m_left_thigh*thigh_center_pos*cos(leg_hip_angle_left - phi) + m_left_shank*shank_center_pos*cos(leg_knee_angle_left - leg_hip_angle_left + phi),                      -m_left_shank*shank_center_pos*cos(leg_knee_angle_left - leg_hip_angle_left + phi), m_right_shank*thigh_length*cos(leg_hip_angle_right - phi) + m_right_thigh*thigh_center_pos*cos(leg_hip_angle_right - phi) + m_right_shank*shank_center_pos*cos(leg_knee_angle_right - leg_hip_angle_right + phi),                      -m_right_shank*shank_center_pos*cos(leg_knee_angle_right - leg_hip_angle_right + phi);
    0,                                                                                                                                                                                                                                                                                                                                                                                            M + m_left_thigh + m_left_shank + m_right_thigh + m_right_shank, m_left_shank*shank_center_pos*sin(leg_knee_angle_left - leg_hip_angle_left + phi) - m_left_shank*thigh_length*sin(leg_hip_angle_left - phi) - m_left_thigh*thigh_center_pos*sin(leg_hip_angle_left - phi) - m_right_shank*thigh_length*sin(leg_hip_angle_right - phi) - m_right_thigh*thigh_center_pos*sin(leg_hip_angle_right - phi) - M*trunk_center_pos*sin(phi) + m_right_shank*shank_center_pos*sin(leg_knee_angle_right - leg_hip_angle_right + phi), m_left_shank*thigh_length*sin(leg_hip_angle_left - phi) + m_left_thigh*thigh_center_pos*sin(leg_hip_angle_left - phi) - m_left_shank*shank_center_pos*sin(leg_knee_angle_left - leg_hip_angle_left + phi),                       m_left_shank*shank_center_pos*sin(leg_knee_angle_left - leg_hip_angle_left + phi), m_right_shank*thigh_length*sin(leg_hip_angle_right - phi) + m_right_thigh*thigh_center_pos*sin(leg_hip_angle_right - phi) - m_right_shank*shank_center_pos*sin(leg_knee_angle_right - leg_hip_angle_right + phi),                       m_right_shank*shank_center_pos*sin(leg_knee_angle_right - leg_hip_angle_right + phi);
    M*trunk_center_pos*cos(phi) - m_left_thigh*thigh_center_pos*cos(leg_hip_angle_left - phi) - m_right_shank*thigh_length*cos(leg_hip_angle_right - phi) - m_right_thigh*thigh_center_pos*cos(leg_hip_angle_right - phi) - m_left_shank*shank_center_pos*cos(leg_knee_angle_left - leg_hip_angle_left + phi) - m_right_shank*shank_center_pos*cos(leg_knee_angle_right - leg_hip_angle_right + phi) - m_left_shank*thigh_length*cos(leg_hip_angle_left - phi), m_left_shank*shank_center_pos*sin(leg_knee_angle_left - leg_hip_angle_left + phi) - m_left_shank*thigh_length*sin(leg_hip_angle_left - phi) - m_left_thigh*thigh_center_pos*sin(leg_hip_angle_left - phi) - m_right_shank*thigh_length*sin(leg_hip_angle_right - phi) - m_right_thigh*thigh_center_pos*sin(leg_hip_angle_right - phi) - M*trunk_center_pos*sin(phi) + m_right_shank*shank_center_pos*sin(leg_knee_angle_right - leg_hip_angle_right + phi),                                                  2*I1_2 + 2*I2_2 + Itrunk2 + M*trunk_center_pos^2 + m_left_shank*shank_center_pos^2 + m_right_shank*shank_center_pos^2 + m_left_shank*thigh_length^2 + m_left_thigh*thigh_center_pos^2 + m_right_shank*thigh_length^2 + m_right_thigh*thigh_center_pos^2 + 2*m_left_shank*shank_center_pos*thigh_length*cos(leg_knee_angle_left) + 2*m_right_shank*shank_center_pos*thigh_length*cos(leg_knee_angle_right),                          - m_left_shank*shank_center_pos^2 - 2*m_left_shank*cos(leg_knee_angle_left)*shank_center_pos*thigh_length - m_left_shank*thigh_length^2 - m_left_thigh*thigh_center_pos^2 - I1_2,   m_left_shank*shank_center_pos^2 + m_left_shank*thigh_length*cos(leg_knee_angle_left)*shank_center_pos,                            - m_right_shank*shank_center_pos^2 - 2*m_right_shank*cos(leg_knee_angle_right)*shank_center_pos*thigh_length - m_right_shank*thigh_length^2 - m_right_thigh*thigh_center_pos^2 - I1_2,   m_right_shank*shank_center_pos^2 + m_right_shank*thigh_length*cos(leg_knee_angle_right)*shank_center_pos;
    m_left_shank*thigh_length*cos(leg_hip_angle_left - phi) + m_left_thigh*thigh_center_pos*cos(leg_hip_angle_left - phi) + m_left_shank*shank_center_pos*cos(leg_knee_angle_left - leg_hip_angle_left + phi),                                                                                                                                                                                                                                                  m_left_shank*thigh_length*sin(leg_hip_angle_left - phi) + m_left_thigh*thigh_center_pos*sin(leg_hip_angle_left - phi) - m_left_shank*shank_center_pos*sin(leg_knee_angle_left - leg_hip_angle_left + phi),                                                                                                                                                                                                                                                                           - m_left_shank*shank_center_pos^2 - 2*m_left_shank*cos(leg_knee_angle_left)*shank_center_pos*thigh_length - m_left_shank*thigh_length^2 - m_left_thigh*thigh_center_pos^2 - I1_2,                            m_left_shank*shank_center_pos^2 + 2*m_left_shank*cos(leg_knee_angle_left)*shank_center_pos*thigh_length + m_left_shank*thigh_length^2 + m_left_thigh*thigh_center_pos^2 + I1_2, - m_left_shank*shank_center_pos^2 - m_left_shank*thigh_length*cos(leg_knee_angle_left)*shank_center_pos,                                                                                                                                                                                                                0,                                                                                                          0;
    -m_left_shank*shank_center_pos*cos(leg_knee_angle_left - leg_hip_angle_left + phi),                                                                                                                                                                                                                                                                                                                                                                          m_left_shank*shank_center_pos*sin(leg_knee_angle_left - leg_hip_angle_left + phi),                                                                                                                                                                                                                                                                                                                                                      m_left_shank*shank_center_pos^2 + m_left_shank*thigh_length*cos(leg_knee_angle_left)*shank_center_pos,                                                                                                   - m_left_shank*shank_center_pos^2 - m_left_shank*thigh_length*cos(leg_knee_angle_left)*shank_center_pos,                                                                         m_left_shank*shank_center_pos^2,                                                                                                                                                                                                                0,                                                                                                          0;
    m_right_shank*thigh_length*cos(leg_hip_angle_right - phi) + m_right_thigh*thigh_center_pos*cos(leg_hip_angle_right - phi) + m_right_shank*shank_center_pos*cos(leg_knee_angle_right - leg_hip_angle_right + phi),                                                                                                                                                                                                                                           m_right_shank*thigh_length*sin(leg_hip_angle_right - phi) + m_right_thigh*thigh_center_pos*sin(leg_hip_angle_right - phi) - m_right_shank*shank_center_pos*sin(leg_knee_angle_right - leg_hip_angle_right + phi),                                                                                                                                                                                                                                                                      - m_right_shank*shank_center_pos^2 - 2*m_right_shank*cos(leg_knee_angle_right)*shank_center_pos*thigh_length - m_right_shank*thigh_length^2 - m_right_thigh*thigh_center_pos^2 - I1_2,                                                                                                                                                                                                         0,                                                                                                       0,                              m_right_shank*shank_center_pos^2 + 2*m_right_shank*cos(leg_knee_angle_right)*shank_center_pos*thigh_length + m_right_shank*thigh_length^2 + m_right_thigh*thigh_center_pos^2 + I1_2, - m_right_shank*shank_center_pos^2 - m_right_shank*thigh_length*cos(leg_knee_angle_right)*shank_center_pos;
    -m_right_shank*shank_center_pos*cos(leg_knee_angle_right - leg_hip_angle_right + phi),                                                                                                                                                                                                                                                                                                                                                                       m_right_shank*shank_center_pos*sin(leg_knee_angle_right - leg_hip_angle_right + phi),                                                                                                                                                                                                                                                                                                                                                   m_right_shank*shank_center_pos^2 + m_right_shank*thigh_length*cos(leg_knee_angle_right)*shank_center_pos,                                                                                                                                                                                                         0,                                                                                                       0,                                                                                                       - m_right_shank*shank_center_pos^2 - m_right_shank*thigh_length*cos(leg_knee_angle_right)*shank_center_pos,                                                                           m_right_shank*shank_center_pos^2];
 
 

 
RHS =[                                                                       F1x + F2x + dleg_hip_angle_left^2*m_left_shank*thigh_length*sin(leg_hip_angle_left - phi) + dleg_hip_angle_left^2*m_left_thigh*thigh_center_pos*sin(leg_hip_angle_left - phi) + dleg_hip_angle_right^2*m_right_shank*thigh_length*sin(leg_hip_angle_right - phi) + dleg_hip_angle_right^2*m_right_thigh*thigh_center_pos*sin(leg_hip_angle_right - phi) + dphi^2*m_left_shank*thigh_length*sin(leg_hip_angle_left - phi) + dphi^2*m_left_thigh*thigh_center_pos*sin(leg_hip_angle_left - phi) + dphi^2*m_right_shank*thigh_length*sin(leg_hip_angle_right - phi) + dphi^2*m_right_thigh*thigh_center_pos*sin(leg_hip_angle_right - phi) - dleg_hip_angle_left^2*m_left_shank*shank_center_pos*sin(leg_knee_angle_left - leg_hip_angle_left + phi) - dleg_knee_angle_left^2*m_left_shank*shank_center_pos*sin(leg_knee_angle_left - leg_hip_angle_left + phi) - dleg_hip_angle_right^2*m_right_shank*shank_center_pos*sin(leg_knee_angle_right - leg_hip_angle_right + phi) - dleg_knee_angle_right^2*m_right_shank*shank_center_pos*sin(leg_knee_angle_right - leg_hip_angle_right + phi) - dphi^2*m_left_shank*shank_center_pos*sin(leg_knee_angle_left - leg_hip_angle_left + phi) - dphi^2*m_right_shank*shank_center_pos*sin(leg_knee_angle_right - leg_hip_angle_right + phi) + M*dphi^2*trunk_center_pos*sin(phi) - 2*dleg_hip_angle_left*dphi*m_left_shank*thigh_length*sin(leg_hip_angle_left - phi) - 2*dleg_hip_angle_left*dphi*m_left_thigh*thigh_center_pos*sin(leg_hip_angle_left - phi) - 2*dleg_hip_angle_right*dphi*m_right_shank*thigh_length*sin(leg_hip_angle_right - phi) - 2*dleg_hip_angle_right*dphi*m_right_thigh*thigh_center_pos*sin(leg_hip_angle_right - phi) + 2*dleg_hip_angle_left*dleg_knee_angle_left*m_left_shank*shank_center_pos*sin(leg_knee_angle_left - leg_hip_angle_left + phi) + 2*dleg_hip_angle_right*dleg_knee_angle_right*m_right_shank*shank_center_pos*sin(leg_knee_angle_right - leg_hip_angle_right + phi) + 2*dleg_hip_angle_left*dphi*m_left_shank*shank_center_pos*sin(leg_knee_angle_left - leg_hip_angle_left + phi) - 2*dleg_knee_angle_left*dphi*m_left_shank*shank_center_pos*sin(leg_knee_angle_left - leg_hip_angle_left + phi) + 2*dleg_hip_angle_right*dphi*m_right_shank*shank_center_pos*sin(leg_knee_angle_right - leg_hip_angle_right + phi) - 2*dleg_knee_angle_right*dphi*m_right_shank*shank_center_pos*sin(leg_knee_angle_right - leg_hip_angle_right + phi);
F1z + F2z - M*g - g*m_left_thigh - g*m_left_shank - g*m_right_thigh - g*m_right_shank - dleg_hip_angle_left^2*m_left_shank*thigh_length*cos(leg_hip_angle_left - phi) - dleg_hip_angle_left^2*m_left_thigh*thigh_center_pos*cos(leg_hip_angle_left - phi) - dleg_hip_angle_right^2*m_right_shank*thigh_length*cos(leg_hip_angle_right - phi) - dleg_hip_angle_right^2*m_right_thigh*thigh_center_pos*cos(leg_hip_angle_right - phi) - dphi^2*m_left_shank*thigh_length*cos(leg_hip_angle_left - phi) - dphi^2*m_left_thigh*thigh_center_pos*cos(leg_hip_angle_left - phi) - dphi^2*m_right_shank*thigh_length*cos(leg_hip_angle_right - phi) - dphi^2*m_right_thigh*thigh_center_pos*cos(leg_hip_angle_right - phi) - dleg_hip_angle_left^2*m_left_shank*shank_center_pos*cos(leg_knee_angle_left - leg_hip_angle_left + phi) - dleg_knee_angle_left^2*m_left_shank*shank_center_pos*cos(leg_knee_angle_left - leg_hip_angle_left + phi) - dleg_hip_angle_right^2*m_right_shank*shank_center_pos*cos(leg_knee_angle_right - leg_hip_angle_right + phi) - dleg_knee_angle_right^2*m_right_shank*shank_center_pos*cos(leg_knee_angle_right - leg_hip_angle_right + phi) - dphi^2*m_left_shank*shank_center_pos*cos(leg_knee_angle_left - leg_hip_angle_left + phi) - dphi^2*m_right_shank*shank_center_pos*cos(leg_knee_angle_right - leg_hip_angle_right + phi) + M*dphi^2*trunk_center_pos*cos(phi) + 2*dleg_hip_angle_left*dphi*m_left_shank*thigh_length*cos(leg_hip_angle_left - phi) + 2*dleg_hip_angle_left*dphi*m_left_thigh*thigh_center_pos*cos(leg_hip_angle_left - phi) + 2*dleg_hip_angle_right*dphi*m_right_shank*thigh_length*cos(leg_hip_angle_right - phi) + 2*dleg_hip_angle_right*dphi*m_right_thigh*thigh_center_pos*cos(leg_hip_angle_right - phi) + 2*dleg_hip_angle_left*dleg_knee_angle_left*m_left_shank*shank_center_pos*cos(leg_knee_angle_left - leg_hip_angle_left + phi) + 2*dleg_hip_angle_right*dleg_knee_angle_right*m_right_shank*shank_center_pos*cos(leg_knee_angle_right - leg_hip_angle_right + phi) + 2*dleg_hip_angle_left*dphi*m_left_shank*shank_center_pos*cos(leg_knee_angle_left - leg_hip_angle_left + phi) - 2*dleg_knee_angle_left*dphi*m_left_shank*shank_center_pos*cos(leg_knee_angle_left - leg_hip_angle_left + phi) + 2*dleg_hip_angle_right*dphi*m_right_shank*shank_center_pos*cos(leg_knee_angle_right - leg_hip_angle_right + phi) - 2*dleg_knee_angle_right*dphi*m_right_shank*shank_center_pos*cos(leg_knee_angle_right - leg_hip_angle_right + phi);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      F1z*shank_length*sin(leg_knee_angle_left - leg_hip_angle_left + phi) - F2x*thigh_length*cos(leg_hip_angle_right - phi) - F1z*thigh_length*sin(leg_hip_angle_left - phi) - F2z*thigh_length*sin(leg_hip_angle_right - phi) - F1x*shank_length*cos(leg_knee_angle_left - leg_hip_angle_left + phi) - F2x*shank_length*cos(leg_knee_angle_right - leg_hip_angle_right + phi) - F1x*thigh_length*cos(leg_hip_angle_left - phi) + F2z*shank_length*sin(leg_knee_angle_right - leg_hip_angle_right + phi) - g*m_left_shank*shank_center_pos*sin(leg_knee_angle_left - leg_hip_angle_left + phi) - g*m_right_shank*shank_center_pos*sin(leg_knee_angle_right - leg_hip_angle_right + phi) + M*g*trunk_center_pos*sin(phi) + g*m_left_shank*thigh_length*sin(leg_hip_angle_left - phi) + g*m_left_thigh*thigh_center_pos*sin(leg_hip_angle_left - phi) + g*m_right_shank*thigh_length*sin(leg_hip_angle_right - phi) + g*m_right_thigh*thigh_center_pos*sin(leg_hip_angle_right - phi) + dleg_knee_angle_left^2*m_left_shank*shank_center_pos*thigh_length*sin(leg_knee_angle_left) + dleg_knee_angle_right^2*m_right_shank*shank_center_pos*thigh_length*sin(leg_knee_angle_right) - 2*dleg_hip_angle_left*dleg_knee_angle_left*m_left_shank*shank_center_pos*thigh_length*sin(leg_knee_angle_left) - 2*dleg_hip_angle_right*dleg_knee_angle_right*m_right_shank*shank_center_pos*thigh_length*sin(leg_knee_angle_right) + 2*dleg_knee_angle_left*dphi*m_left_shank*shank_center_pos*thigh_length*sin(leg_knee_angle_left) + 2*dleg_knee_angle_right*dphi*m_right_shank*shank_center_pos*thigh_length*sin(leg_knee_angle_right);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                tal_hip_left + F1x*thigh_length*cos(leg_hip_angle_left - phi) + F1z*thigh_length*sin(leg_hip_angle_left - phi) + F1x*shank_length*cos(leg_knee_angle_left - leg_hip_angle_left + phi) - F1z*shank_length*sin(leg_knee_angle_left - leg_hip_angle_left + phi) + g*m_left_shank*shank_center_pos*sin(leg_knee_angle_left - leg_hip_angle_left + phi) - g*m_left_shank*thigh_length*sin(leg_hip_angle_left - phi) - g*m_left_thigh*thigh_center_pos*sin(leg_hip_angle_left - phi) - dleg_knee_angle_left^2*m_left_shank*shank_center_pos*thigh_length*sin(leg_knee_angle_left) + 2*dleg_hip_angle_left*dleg_knee_angle_left*m_left_shank*shank_center_pos*thigh_length*sin(leg_knee_angle_left) - 2*dleg_knee_angle_left*dphi*m_left_shank*shank_center_pos*thigh_length*sin(leg_knee_angle_left);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 - m_left_shank*shank_center_pos*thigh_length*sin(leg_knee_angle_left)*dleg_hip_angle_left^2 + 2*m_left_shank*shank_center_pos*thigh_length*sin(leg_knee_angle_left)*dleg_hip_angle_left*dphi - m_left_shank*shank_center_pos*thigh_length*sin(leg_knee_angle_left)*dphi^2 + tal_hip_right - F1x*shank_length*cos(leg_knee_angle_left - leg_hip_angle_left + phi) + F1z*shank_length*sin(leg_knee_angle_left - leg_hip_angle_left + phi) - g*m_left_shank*shank_center_pos*sin(leg_knee_angle_left - leg_hip_angle_left + phi);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        tal_knee_left + F2x*thigh_length*cos(leg_hip_angle_right - phi) + F2z*thigh_length*sin(leg_hip_angle_right - phi) + F2x*shank_length*cos(leg_knee_angle_right - leg_hip_angle_right + phi) - F2z*shank_length*sin(leg_knee_angle_right - leg_hip_angle_right + phi) + g*m_right_shank*shank_center_pos*sin(leg_knee_angle_right - leg_hip_angle_right + phi) - g*m_right_shank*thigh_length*sin(leg_hip_angle_right - phi) - g*m_right_thigh*thigh_center_pos*sin(leg_hip_angle_right - phi) - dleg_knee_angle_right^2*m_right_shank*shank_center_pos*thigh_length*sin(leg_knee_angle_right) + 2*dleg_hip_angle_right*dleg_knee_angle_right*m_right_shank*shank_center_pos*thigh_length*sin(leg_knee_angle_right) - 2*dleg_knee_angle_right*dphi*m_right_shank*shank_center_pos*thigh_length*sin(leg_knee_angle_right);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 - m_right_shank*shank_center_pos*thigh_length*sin(leg_knee_angle_right)*dleg_hip_angle_right^2 + 2*m_right_shank*shank_center_pos*thigh_length*sin(leg_knee_angle_right)*dleg_hip_angle_right*dphi - m_right_shank*shank_center_pos*thigh_length*sin(leg_knee_angle_right)*dphi^2 + tal_knee_right - F2x*shank_length*cos(leg_knee_angle_right - leg_hip_angle_right + phi) + F2z*shank_length*sin(leg_knee_angle_right - leg_hip_angle_right + phi) - g*m_right_shank*shank_center_pos*sin(leg_knee_angle_right - leg_hip_angle_right + phi)];
qdd= MM \ RHS;

ddx=qdd(1);
ddz=qdd(2);
ddphi=qdd(3);
ddleg_hip_angle_left=qdd(4);
ddleg_knee_angle_left=qdd(5);
ddleg_hip_angle_right=qdd(6);
ddleg_knee_angle_right=qdd(7);

zdot=[dx dz dphi dleg_hip_angle_left dleg_knee_angle_left dleg_hip_angle_right dleg_knee_angle_right ...
      ddx ddz ddphi ddleg_hip_angle_left ddleg_knee_angle_left ddleg_hip_angle_right ddleg_knee_angle_right]';

